export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';
export const LOADED_USER_SUCCESS = 'LOADED_USER_SUCCESS';
export const LOADED_USER_FAILED = 'LOADED_USER_FAILED';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED';
export const SIGN_OUT = 'SIGN_OUT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// Theme
export const TOGGLE_LAYOUT_THEME = 'TOGGLE_LAYOUT_THEME';
