export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';
export const LOADED_USER_SUCCESS = 'LOADED_USER_SUCCESS';
export const LOADED_USER_FAILED = 'LOADED_USER_FAILED';
